# Generated by Django 3.0.3 on 2021-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='novel/'),
        ),
    ]
