# Generated by Django 3.0.3 on 2021-05-08 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0005_auto_20210508_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 29, 35, 41798)),
        ),
    ]
