# Generated by Django 3.0.3 on 2021-05-08 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0006_auto_20210508_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 32, 51, 388787)),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
