# Generated by Django 3.0.3 on 2021-05-08 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0010_auto_20210508_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 22, 57, 27, 960986)),
        ),
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 22, 57, 27, 960986)),
        ),
    ]
