# Generated by Django 3.0.3 on 2021-05-08 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0014_auto_20210508_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 23, 51, 3, 21356)),
        ),
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 23, 51, 3, 21356)),
        ),
        migrations.AlterField(
            model_name='setting',
            name='height',
            field=models.CharField(default=24, max_length=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='size',
            field=models.CharField(default=16, max_length=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='width',
            field=models.CharField(default=48, max_length=10),
        ),
    ]
