# Generated by Django 3.0.3 on 2021-05-31 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosull', '0023_auto_20210509_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 16, 10, 34, 474006)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 16, 10, 34, 474006)),
        ),
        migrations.AlterField(
            model_name='marker',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 16, 10, 34, 473040)),
        ),
        migrations.AlterField(
            model_name='novel',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
